AllCops:
        TargetRubyVersion: 2.3

# false positives on inline if-blocks
Layout/ElseAlignment:
        Enabled: false
Layout/EndAlignment:
        Enabled: false

# tabs > spaces
Layout/IndentationWidth:
        Enabled: false
Layout/Tab:
        Enabled: false
Layout/IndentHash:
        Enabled: false

# false positives on clear function calls
Lint/AmbiguousOperator:
        Enabled: false

# too tight margins
Metrics/AbcSize:
        Enabled: false
Metrics/ClassLength:
        Max: 180
Metrics/CyclomaticComplexity:
        Enabled: false
Metrics/LineLength:
        Max: 100
Metrics/MethodLength:
        Max: 40
Metrics/PerceivedComplexity:
        Enabled: false

# style disagreement
Style/ClassAndModuleChildren:
        Enabled: false

# TODO
Style/Documentation:
        Enabled: false
Style/FrozenStringLiteralComment:
        Enabled: false
